### ISSUE TITLE
The keybindings are not as comprehensive

### ISSUE THREAD

**Issue by jcmkk3** [stevenguh/spacecode#8] opened 2020-06-16 04:08 UTC
I'm happy to see a Spacemacs like keybinding and menu scheme brought to vscode. I have tried it out and it already works really well for what it does. Thank you for writing this!

I see that you've already been speaking with @MarcoIeni in another issue. I didn't see him mention it, but he maintains similar extensions for some other editors ([spaceclipse](https://github.com/MarcoIeni/spaceclipse) and [intellimacs](https://github.com/MarcoIeni/intellimacs)). I think that the [keybinding list](https://github.com/MarcoIeni/intellimacs/blob/master/docs/KEYBINDINGS.org) that he created could be especially useful for a new project like this.

**Comment by marcoieni** [comment] 2020-06-16 06:16
Key bindings table could be auto-generated by parsing the json file with a github action.

We could place it in a website deployed with github pages for example.

**Comment by stevenguh** [comment] 2020-06-16 06:54
I am glad you like it, and thank you for sharing those resources. I just realized there are a lot of obvious bindings in spacemacs that I missed in the default bindings. I will try to add some of the obvious ones tomorrow. I'd also love to have the community to sort thourgh the rest of the non-obvious bindings. My philosophy is stay relatively close to spacemacs' default, but I also recognize some commands/concepts are fundamentally different between vscode and emacs which can get tricky and would love any contributions from the community.

> Key bindings table could be auto-generated by parsing the json file with a github action.

That's an awesome idea, since the default bindings in the `package.json` already have enough information to generate a markdown table.

**Comment by marcoieni** [comment] 2020-06-16 20:08
>  I'd also love to have the community to sort thourgh the rest of the non-obvious bindings.

There is the [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode) project where we defined a lot of key bindings. Please check out [this](https://github.com/VSpaceCode/VSpaceCode/issues/45#issuecomment-644982775) issue :)

> That's an awesome idea, since the default bindings in the package.json already have enough information to generate a markdown table.

Yes, this could be labeled as a good first issue

**Comment by stevenguh** [comment] 2020-06-17 05:01
Issue #9 is opened to track the work to create the table. I also renamed this issue to "The keybindings are not as comprehensive" as I think that's what we are getting at here. I will need think a little bit before I form my opinion on the issue on VSpaceCode project.

I made quite a bit of progress of making the default bindings more comprehensive and implemented a basic transient menu. See the unreleased section of the [changelog](https://github.com/stevenguh/spacecode/blob/89046592d9adf455b867864860bd4897766ec1a3/CHANGELOG.md) in develop branch. Feel free to test the code in the develop branch.

There are still some inconsistencies:
- `<SPC> p` - I will look more into this tomorrow
- `<SPC> s` - Currently it's used for show commands. I will probably make a breaking changes to remove the show menu or move it elsewhere tomorrow.
- `<SPC> j` - Not sure if there's a way to tigger easymotion as an external extension. The value of the a `j` menu is diminishing if the only binding left in that menu is to format document which is current covered in `<SPC> f =`.

**Comment by marcoieni** [comment] 2020-06-17 17:41
> Feel free to test the code in the develop branch.

People may not know how to do it (I don't). A guide might help, maybe in a [CONTRIBUTING.md](https://github.com/MarcoIeni/intellimacs/blob/master/docs/CONTRIBUTING.org) file?

**Comment by stevenguh** [comment] 2020-06-17 21:12
That's a great idea. I will put that in my todo radar. In the meantime, to test the project:
1. clone and project
2. checkout develop branch
3. open the folder with vscode
4. Press F5 to run a debug vscode with extension in development installed on that instance.

**Comment by stevenguh** [comment] 2020-06-17 23:32
I looked into project menu, and it's largely duplicate of `<spc> f` I am a little hesitant to add it at this moment unless we have a better file/folder navigation like https://github.com/jit-y/vscode-advanced-open-file. We can potentially integrate another that extension; however, we have many things on the plate like the potential of merging repo/splitting lib. For the next release, I think what we have in develop is a large enough improvement.

**Comment by marcoieni** [comment] 2020-06-18 17:26
I created #10 and [this](https://github.com/VSpaceCode/VSpaceCode/issues/46) other issue.

From [this](https://github.com/VSpaceCode/VSpaceCode/issues/45) discussion it seems that key bindings will be contained in the [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode) repo only.


I agree with Steven that at the moment we should not add other key bindings to this repo and focus on merging the two repositories instead.
Anyway if anyone wants to introduce new key bindings he should open new issues or pull requests in the [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode) repo. They will be usable with this plugin sooner or later 😅

If there are no other open points we could close this issue.

**Comment by stevenguh** [comment] 2020-06-18 20:33
Thanks for creating the issue to track the work :)

The move shouldn't really affect this issue, since the issue hasn't been resolved yet. I can transfer this issue to the VSpaceCode when it is merged.

This issue will be closed on `v0.4.0` release which should include a more complete bindings.

**Comment by stevenguh** [comment] 2020-06-22 19:34
`v0.4.0` is released on `VSpaceCode`. Closing this issue.

**Closed as completed by stevenguh** 2020-06-22 19:34 UTC
